Repository AY2122S1-CS2103T-F11-1/tp, pull requests merged in 2021-11, with the labels that each got.

#224 Fix all documentation bugs pointed out in mock PE
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: priority.Medium

#230 Set character count limit for attributes and update min-width
  src/main/java/seedu/address/commons/util/AppUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tuitionclass/ClassName.java
  src/main/java/seedu/address/model/tuitionclass/Location.java
  src/main/java/seedu/address/model/tuitionclass/Rate.java
  src/main/java/seedu/address/model/util/Commons.java
  src/main/java/seedu/address/ui/studenttab/StudentCard.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/model/ModelTestUtils.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/tuitionclass/ClassNameTest.java
  src/test/java/seedu/address/model/tuitionclass/LocationTest.java
  src/test/java/seedu/address/model/tuitionclass/RateTest.java
Labels: priority.High

#232 fix issues #216, #195, added 1 testcase for overlapping tuitionclasses
  src/main/java/seedu/address/logic/commands/classcommands/EditClassCommand.java
  src/main/java/seedu/address/logic/parser/classcommandparsers/EditClassCommandParser.java
  src/main/java/seedu/address/model/tuitionclass/UniqueClassList.java
  src/test/java/seedu/address/model/tuitionclass/TuitionClassTest.java
Labels: priority.Medium

#234 add UniqueClassListTest
  src/main/java/seedu/address/model/tuitionclass/UniqueClassList.java
  src/test/java/seedu/address/model/tuitionclass/UniqueClassListTest.java
Labels: type.Task, priority.Medium

#239 add PPP for ongzl
  docs/team/ongzl.md
Labels: type.Task, priority.High

#240 list, listclass, class switches to respective tabs, fixed sort command which deletes students unintentionally
  src/main/java/seedu/address/logic/CommandObserver.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SelectClassCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/classcommands/ListClassCommand.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabName.java
  src/main/java/seedu/address/ui/classtab/ClassPanel.java
  src/main/java/seedu/address/ui/classtab/StudentClassPanel.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/ui/TabNameTest.java
Labels: type.Task, priority.High, severity.Medium

#246 fix AddToClassCommand and RemoveFromClassCommand where any of the stu…
  src/main/java/seedu/address/logic/commands/classcommands/AddToClassCommand.java
  src/main/java/seedu/address/logic/commands/classcommands/RemoveFromClassCommand.java
Labels: priority.High

#247 Fix no class shows entire studentlist bug
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/classcommands/FindClassCommand.java
  src/main/java/seedu/address/logic/commands/classcommands/FindClassNameCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/classtab/TuitionClassCard.java
Labels: severity.High

#248 Gui bug fixes
  src/main/java/seedu/address/logic/commands/classcommands/AddToClassCommand.java
  src/main/java/seedu/address/logic/commands/classcommands/RemoveFromClassCommand.java
  src/main/java/seedu/address/logic/commands/classcommands/SelectClassCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/classcommandparsers/SelectClassCommandParser.java
  src/main/java/seedu/address/ui/classtab/TuitionClassCard.java
  src/main/java/seedu/address/ui/classtab/TuitionClassListViewCell.java
  src/main/resources/view/classTab/ClassPanel.fxml
Labels: priority.Medium, hacktoberfest-accepted

#249 Fix unhandled exceptions when invalid indexes are entered with Delete…
  src/main/java/seedu/address/logic/commands/classcommands/DeleteClassCommand.java
Labels: priority.High

#250 Branch fix sort command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/classcommands/RemoveFromClassCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tuitionclass/StudentNameList.java
  src/main/java/seedu/address/ui/classtab/TuitionClassCard.java
  src/main/java/seedu/address/ui/timetabletab/TimetablePanel.java
  src/main/java/seedu/address/ui/timetabletab/TimetableRegion.java
  src/main/resources/view/timetableTab/Timetable.css
  src/main/resources/view/timetableTab/TimetableDay.fxml
  src/main/resources/view/timetableTab/TimetablePanel.fxml
  src/main/resources/view/timetableTab/TimetableTuitionClassSlot.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task, type.Bug, priority.High

#251 Fix unhandled exceptions when invalid class indexes are entered with …
  src/main/java/seedu/address/logic/commands/classcommands/RemoveFromClassCommand.java
Labels: type.Bug, priority.High

#252 Fix unhandled exceptions when invalid class indexes are entered with …
  src/main/java/seedu/address/logic/commands/classcommands/AddToClassCommand.java
  src/main/java/seedu/address/logic/commands/classcommands/RemoveFromClassCommand.java
  src/main/java/seedu/address/logic/parser/classcommandparsers/AddToClassCommandParser.java
  src/main/java/seedu/address/logic/parser/classcommandparsers/RemoveFromClassCommandParser.java
  src/test/java/seedu/address/logic/parser/classcommands/AddToClassCommandParserTest.java
Labels: priority.High

#256 Add tests for sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/testutil/TypicalTimestable.java
Labels: priority.High

#259 Branch add add class command test
  src/main/java/seedu/address/logic/commands/classcommands/AddClassCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/classcommands/AddClassCommandTest.java
  src/test/java/seedu/address/logic/parser/classcommands/AddClassCommandParserTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
Labels: priority.High

#261 Remove ScheduleCommand and its parser and relevant tests
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
Labels: priority.Medium

#265 Update PPP and use cases in DG
  docs/DeveloperGuide.md
  docs/team/ongzl.md
Labels: priority.High

#282 Stuart PPP first draft
  docs/team/s7u4rt99.md
Labels: type.Task, priority.High

#281 Add JsonAdaptedTuitionClassTest and update UG to notify users that fi…
  docs/UserGuide.md
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTuitionClassTest.java
Labels: priority.High

#283 Change name comparison to ignore case.
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/StudentTest.java
Labels: type.Bug, severity.Medium

#297 Add Timetable UI implementation to DG
  docs/DeveloperGuide.md
  docs/diagrams/BuildTimetableDayActivityDiagram.puml
  docs/diagrams/BuildTimetableHeaderActivityDiagram.puml
  docs/diagrams/BuildTimetableOverallDiagram.puml
  docs/diagrams/BuildTimetableTuitionClassSlotsActivityDiagram.puml
  docs/diagrams/FindEarliestAndLatestHourActivityDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/TimetableDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/BuildTimetableDayActivityDiagram-Activity__Build_TimetableDay.png
  docs/images/BuildTimetableHeaderActivityDiagram-Activity__Build_TimetableHeader.png
  docs/images/BuildTimetableOverallDiagram.png
  docs/images/BuildTimetableTuitionClassSlotsActivityDiagram-Activity__Build_TimetableTuitionClassSlots.png
  docs/images/FindEarliestAndLatestHourActivityDiagram-Activity__Find_earliest_start_hour_and_latest_end_hour.png
  docs/images/LogicClassDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/images/TimetableAnnotation.png
  docs/images/TimetableDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/ViewSequenceDiagram.png
  src/main/java/seedu/times/logic/commands/SortCommand.java
  src/main/java/seedu/times/model/Model.java
  src/main/java/seedu/times/model/ModelManager.java
  src/main/java/seedu/times/ui/timetabletab/TimetablePanel.java
  src/test/java/seedu/times/logic/commands/AddCommandTest.java
  src/test/java/seedu/times/logic/commands/classcommands/AddClassCommandTest.java
  src/test/java/seedu/times/logic/commands/classcommands/RemoveFromClassCommandTest.java
Labels: priority.High

#310 Add sort and view feature to DG
  docs/DeveloperGuide.md
  docs/diagrams/ClassPanelDiagram.puml
  docs/diagrams/StudentsDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/StudentsDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.High

#314 Edit DG, PPP and improve code quality
  docs/DeveloperGuide.md
  docs/team/s7u4rt99.md
  src/main/java/seedu/times/logic/commands/ViewCommand.java
  src/main/java/seedu/times/model/tuitionclass/ClassTiming.java
  src/main/java/seedu/times/ui/MainWindow.java
  src/main/java/seedu/times/ui/classtab/StudentClassPanel.java
  src/main/java/seedu/times/ui/classtab/TuitionClassPanel.java
  src/main/java/seedu/times/ui/timetabletab/TimetablePanel.java
  src/main/java/seedu/times/ui/timetabletab/TimetableTuitionClassSlot.java
Labels: priority.High

#322 Edit DG
  docs/DeveloperGuide.md
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/SortSequenceDiagram.png
  docs/images/ViewSequenceDiagram.png
Labels: priority.High

#334 Add manual testing for list, clear, addclass, findclassname
  docs/DeveloperGuide.md
  src/main/java/seedu/times/logic/commands/ClearCommand.java
  src/main/java/seedu/times/logic/commands/FindNameCommand.java
  src/main/java/seedu/times/logic/commands/FindTagCommand.java
  src/main/java/seedu/times/logic/commands/classcommands/FindClassCommand.java
  src/main/java/seedu/times/logic/commands/classcommands/FindClassNameCommand.java
Labels: priority.High
